---
all:
  vars:
    ansible_user: test
    ansible_ssh_pass: test
    working_path: "/home/test"
    working_path_cron: "/home/test/bin"
    new_dir: "bin"
    file: "x.sh"

  children:
    prod:
      hosts:
        agent1:
    staging:
      hosts:
        agent2:
        agent3:

ungrouped:
  hosts:
    localhost
  vars:
    ansible_connection: local
